#!/bin/bash
echo "enter file name"
      read filename
      
while true; do
  echo "Select an option:"
  echo "1. Enter a sentence into a file"
  echo "2. Search for a given whole word in an existing file"
  echo "3. Quit"
  read choice

  case $choice in
    1)
  
      echo "Enter sentence:"
      read sentence
      echo "$sentence" > "$filename"
      echo "Sentence saved to file"
      ;;
    2)
      echo "Enter word to search for:"
      read word
      if [ -f "$filename" ]; then
        if grep -q "\<$word\>" "$filename"; then
          echo "Word found in file"
        else
          echo "Word not found in file"
        fi
      else
        echo "File not found"
      fi
      ;;
    3)
      echo "Exiting program"
      exit 0
      ;;
    *)
      echo "Invalid choice"
      ;;
  esac

done
